### ISSUE TITLE
The function "form_close" does not exist 

### ISSUE THREAD

**Issue by huglester** [rcrowe/TwigBridge#209]
Hello,

I just installed TwigBridge, so far extention is working. It finds the views,
I have installed laravelcollective/html and forms.

But when doind {{ form_close() }} I get this: The function "form_close" does not exist 

What I may be doing wrong?

Thanks!

**Comment by barryvdh** [comment]
Did you enable the form extension in your twigbridge config?

**Comment by harwin-borger** [comment]
Hey, 

I think this is a bug, since I am new to Laravel I can not fix it yet. The following error I get:
       Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Form': Class Collective\Html\FormBuilder does not exist 

What I found out is the following thing: 
When you go to Form.php line 16, you find the following rule:
      use Collective\Html\FormBuilder;

However this Class does not exists any longer in Laravel 5. 

I hope someone has the knowledge to repair it.

**Comment by barryvdh** [comment]
You need to require the collective html/form package in your composer file.

**Comment by jordanlev** [comment]
I had the same issue and it took a long confusing time to track down the solution (I'm brand new to Laravel), so I made a [pull request to explain how to get this working](https://github.com/rcrowe/TwigBridge/pull/220) in the README file.
