### ISSUE TITLE
How to access laravel functions in the twig

### ISSUE THREAD

**Issue by kala725** [rcrowe/TwigBridge#222]
1. I want to use env('VERSION') , variable inside twig, but it is saying `The function "env" does not exist in "base" `

2. To use Cdn::asset() function of vinelab cdn , it is giving me the error `Unexpected token "punctuation" of value ":" ("end of print statement" expected)`

**Comment by octavhendra** [comment]
1. you can add function in twigbridge.php inside function array.
2. First, you have to add Cdn facade inside facade array in twigbridge.php and you can call Cdn.asset()

**Comment by shehi** [comment]
Search ```helpers.php``` file for a function with "env" word in it. I believe there should be ```getenv()``` somewhere there.

**Comment by kala725** [comment]
I also got a solution...


Just add env in the functions array in config/twigbridge.php and it works well.

**Comment by kwoodfriend** [comment]
Here's my solution. If you find that you're using a PHP function a lot, you should add it to the twigbridge config file. Otherwise, below can be used for "quick fixes". It uses PHP 5.6 features, so make sure to update if you're using something lower.

FuncProxy class:

```php
// app/Twig/FuncProxy.php

<?php

namespace App\Twig;

class FuncProxy
{
    public function __call($func, $args)
    {
        if (function_exists($func)) {
            return $func(...$args);
        } else {
            // You might want to do something else here, like throw an exception.
            return null;
        }
    }
}

```

And a global instance of the class. You're welcome to change the global's name, but I find "PHP" to be helpful, so that I know I'm using the function proxy. You could also use something like "Func", etc.

```php
// config/twigbridge.php

// ...

'globals' => [
    'PHP' => new \App\Twig\FuncProxy(),
],
// ...
```

Then in your twig files:

```twig

<span>{{ PHP.ucfirst('foobar baz') }}</span>
```

This doesn't support namespaced functions, static method, etc.

**Comment by kala725** [comment]
Thanks @kfriend for a global solution.
