### ISSUE TITLE
Example custom filter extension request

### ISSUE THREAD

**Issue by gavinhewitt** [rcrowe/TwigBridge#83]
I'm a little lost as how to add custom filters to Twigbridge. Yes, I've read the documentation but I just can't figure it out. I need an 'unserialize' filter, would be really grateful if someone could whip up an example. 

Thanks in advance!

**Comment by ajhsu** [comment]
Just ran into the same question, decided to leave a quick note here:

Once you decide to write your own custom filter with TwigBridge,
just open up the file `config/twigbridge.php` and jump to `'filters' => []` section;

Then the simplest way to add your own filter, is by writing an anonymous function like:

```php
'filters' => [
    'site_prefix' => function ($string) {
        return env('SITE_PREFIX') . $string;
    }
]
```

So that you can use it in Twig like:

```twig
<script src="{{ '/assets/pages/home.js' | site_prefix }}"></script>
```

Some other ways can be referenced from Twig official document:
https://twig.symfony.com/doc/1.x/advanced.html#filters

**Comment by ajhsu** [comment]
Also note that comments from `config/twigbridge.php` gives a great explanation about it:
https://github.com/rcrowe/TwigBridge/blob/master/config/twigbridge.php#L186
